# Generated by Django 5.2.8 on 2025-11-15 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('brickbasket', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='subname',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
